import React from 'react'
import classes from "./BlogMain.module.css"
import Card from '../UI/Card/Card'
const BlogMain = () => {
  return (
    <main>
      <Card>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Optio, sed dolor doloribus eius vero perferendis nesciunt. Assumenda, eligendi nihil nostrum quasi sapiente impedit explicabo iste, quos, tenetur laudantium saepe tempora?
        Nam, doloribus! Sequi maiores earum repellendus at cum dicta consequatur natus laborum vel veniam? Architecto ea debitis aut placeat doloremque fuga natus, in dolorem, corrupti ex provident voluptates! Perferendis, nihil?
        In quia dolorum a delectus distinctio fugiat veniam, nisi fugit, neque necessitatibus quasi, modi esse! Saepe esse rem delectus eius unde. Aut, in mollitia. Quaerat esse error hic non quod.
        Fuga asperiores, expedita saepe et rem a eveniet qui commodi dolore nihil eligendi vitae ex ducimus nemo ipsam magnam sit nulla voluptates! Ratione architecto sint eaque. Alias aliquam ullam ab.
        Modi exercitationem corrupti ab dolore, iste temporibus a aliquid ipsa eveniet nostrum reiciendis obcaecati deleniti doloremque neque, labore velit voluptates, ipsam recusandae cumque accusantium repellendus iusto sunt alias? At, nostrum.
        Sint, molestias asperiores in ipsa error iusto quae obcaecati animi. Placeat et similique recusandae, impedit optio obcaecati ea saepe eaque vero omnis aspernatur nostrum expedita nulla dolores vitae quidem odio.
        Harum quae aliquid impedit eius iste repudiandae ratione nihil cum quis laudantium. Temporibus, soluta itaque a vitae adipisci delectus voluptatibus ratione! Autem similique inventore rerum suscipit recusandae, atque pariatur molestiae.
        Sed odio, corrupti optio atque amet eum voluptatibus assumenda voluptatum, aliquid, laborum quia similique earum. Voluptatem dicta nisi exercitationem atque, id debitis autem. Nam expedita sequi ullam rem doloremque quas.
        Ullam eligendi modi quod necessitatibus itaque temporibus consequatur repellat. Cum odit sapiente commodi assumenda, provident reiciendis, sunt odio nobis architecto veritatis, ipsa possimus? Dignissimos, rerum est suscipit qui optio quo?
        Nihil recusandae dicta eligendi magnam. Hic vitae nostrum, reiciendis iste reprehenderit, beatae, tempore error dolor pariatur ipsum nulla fuga magni alias quae accusantium omnis rerum totam debitis laudantium voluptas harum?
        Explicabo neque sunt optio aperiam veniam fuga non asperiores, maxime dolorum adipisci distinctio obcaecati beatae tempora odio facilis numquam incidunt velit nemo ipsum, quibusdam nihil. Porro, reiciendis? Tempore, atque sit?
        At, delectus fugit! Est labore mollitia soluta eveniet alias voluptatibus ratione reprehenderit ducimus modi accusantium maiores officiis repellat veritatis nobis, neque, voluptate a ab id aut quidem quas. Rerum, ab.
        Hic alias quae, adipisci totam repudiandae corporis facere eligendi dolorem labore sequi. Eius nam pariatur possimus nesciunt, quidem unde rem veniam. Exercitationem dolores harum quae id officiis non! Doloremque, cum!
        Possimus quis porro impedit, ullam reprehenderit, debitis animi repellat provident voluptas voluptate harum architecto molestiae? Itaque, molestiae. Soluta ipsum omnis necessitatibus dolores voluptatem quasi voluptates, repellat autem tempore, illo dolor.
        Quasi repudiandae illo impedit voluptatum omnis accusamus autem possimus velit deleniti, quidem quo? Facilis tenetur quod natus quia sunt, facere voluptatibus rerum? Consectetur necessitatibus reiciendis natus mollitia sit minus nobis.
        Nobis saepe quos dolores odit odio impedit nisi vero quia corporis eum, unde natus quas quasi expedita non, neque enim ex tenetur quo, exercitationem cum hic? Maiores facere ipsam asperiores.
        Obcaecati repellendus soluta consectetur explicabo quam! Fuga eveniet perspiciatis ullam officia facilis reprehenderit sed ipsam praesentium corporis eius inventore voluptate, non molestiae quisquam odit nemo obcaecati nisi dicta ut repellendus.
        Deleniti explicabo consequatur nisi minus assumenda perspiciatis aliquid. Nesciunt, quis earum sapiente necessitatibus ipsam eligendi tempora expedita magnam maxime modi esse. Ipsa autem cumque odio et eveniet architecto corporis cum.
        Ex iusto saepe iure recusandae maxime consequuntur mollitia repellat pariatur minus perferendis sed reiciendis beatae, repellendus necessitatibus delectus dolorem architecto incidunt, dicta enim fugit, provident debitis molestias. Necessitatibus, aspernatur voluptas?
        Officiis, explicabo ut illo minima quibusdam id beatae quidem soluta, totam atque, velit quos doloremque quis repellendus unde voluptates vero voluptatum culpa voluptate earum deleniti. Labore repellendus nulla doloremque ut.
        Mollitia necessitatibus, incidunt aut voluptas maxime debitis quas voluptate numquam placeat obcaecati consequuntur quos commodi, hic harum officia quibusdam dolorem excepturi ab, maiores corporis nulla eligendi. Magni, tempore dolorum! Ullam.
        Ad velit ratione error fugit, dolor accusamus maiores corrupti alias molestias ducimus, sed vitae nisi cumque ipsam perspiciatis eos nobis. Vero iste quod doloribus autem, iusto eius reprehenderit ratione quos.
        Laudantium eos laboriosam praesentium officia sequi optio magni est sit adipisci labore omnis doloremque, inventore veritatis reiciendis nemo dolorem cupiditate quod maxime tenetur quis nisi. Pariatur voluptatum est nihil nam!
        Dignissimos doloribus beatae illum cumque vero consectetur fuga voluptatem, hic totam rerum tenetur dolorum rem! Sunt, neque? Id dolores maxime sunt, placeat nisi possimus rerum consequatur eaque ea obcaecati debitis.
        Voluptate ipsa necessitatibus quaerat accusantium adipisci animi culpa! Laborum omnis nemo consequatur, ea voluptatum, doloremque fugiat, minus dignissimos architecto praesentium ullam deserunt doloribus fugit expedita molestiae repudiandae ad obcaecati reprehenderit.
        Nobis, repellat in! Adipisci error omnis laboriosam maxime facere praesentium eveniet quia. Ipsa odit voluptatem eos a quaerat debitis? Eius repellat reprehenderit voluptates molestiae esse porro autem corporis exercitationem sint!
        Distinctio repellendus eius atque eaque dolorem dolor laudantium blanditiis quis expedita magnam officiis, veritatis temporibus ducimus dolores officia aliquid quae architecto laboriosam, delectus culpa sequi harum! Ea ratione consequuntur quam!
        Harum vero at exercitationem illum aut debitis totam maxime dolorem magnam quia, fuga, ipsum temporibus cumque beatae sint. Laudantium aliquam nam ratione maxime obcaecati dolorem similique aperiam consequatur tempore? Commodi.
        Ratione voluptatum aliquam culpa quibusdam, maiores commodi consectetur tenetur tempore quae sint dolores laudantium fuga distinctio similique aspernatur odit architecto adipisci sit praesentium, cumque maxime accusamus? Ab dicta magni beatae.
        Quidem ad ullam nesciunt placeat recusandae rerum fugiat nulla explicabo architecto. Aperiam unde harum soluta, impedit earum sit? Sit, omnis. Totam provident veniam eos sapiente sint eum dignissimos tenetur voluptatibus!
        Ut nam natus maiores? Voluptas autem veniam cupiditate perferendis delectus iusto vel repellat asperiores dolore, et pariatur, totam ipsa officiis optio voluptates harum veritatis obcaecati temporibus rerum molestiae dignissimos corporis!
        Eveniet velit nam qui quia magnam. Facilis est fugit, veritatis iusto consequuntur ex sed vel voluptatem nostrum quo officia ipsum reiciendis temporibus ipsa fugiat, inventore accusantium rerum. Ex, ipsam dolores!
        A sit est suscipit eius qui nemo aspernatur quis labore, facere nam ex officia voluptatum alias cupiditate iusto pariatur fuga consectetur quae perspiciatis ratione ipsam quam. Expedita provident voluptatum nihil?
        Aut voluptatem, molestiae cumque autem soluta officiis fugiat expedita, perferendis velit consequatur numquam quia ut, dicta obcaecati neque harum maxime esse nam dolorum voluptatum. Perferendis reiciendis distinctio quia molestiae praesentium.
        Minus, quia in reprehenderit magni aliquam perferendis dolore est! Rerum eius error sapiente? Consectetur odit quos aut nostrum provident molestias quae expedita temporibus ipsa, repellat fuga velit magnam esse adipisci!
        Perferendis saepe quam, dolores voluptatem illum atque magni maxime reprehenderit deleniti ipsum iure deserunt pariatur? In quae cupiditate iste! Mollitia praesentium iusto ratione odio at ipsum fugit nulla eum ab.
        Illum consequuntur earum magni quod natus, velit ex sit porro! Aspernatur magnam eius consequatur quod saepe architecto vitae assumenda, odit cupiditate quia fugiat blanditiis enim? Qui, eligendi expedita. Soluta, atque.
        Reiciendis harum odit repudiandae commodi ipsum iste. Earum atque iste ea laboriosam nulla laborum in ipsam eum voluptate maxime illum rerum adipisci, expedita inventore non optio facilis porro quod aperiam.
        Doloremque repellendus officia perferendis nisi corrupti ad voluptatem, minus culpa. Quod, iure laboriosam sint repudiandae ratione incidunt fugiat praesentium. Nisi eius iure consectetur, beatae maiores magni dicta quibusdam ullam nesciunt?
        Qui necessitatibus quod quidem! Tempora ex facere aspernatur doloribus sed quas alias sapiente, quis, eum ab quod accusamus illum sunt accusantium. Iusto unde minima hic ea magnam quis incidunt ipsa.
        Provident fugiat dolore quia, dolorum suscipit natus magnam voluptates ullam placeat est ut officia adipisci! A quaerat dolores ipsum eveniet aperiam praesentium quis, illum sapiente facilis omnis eaque maiores corrupti.
        Quia dolorum incidunt distinctio voluptates aperiam omnis possimus animi magni excepturi consequuntur quod suscipit magnam reiciendis sunt illo, doloribus, inventore veritatis veniam sed! Ex, quisquam reiciendis! Dolor, laborum. Doloremque, magni.
        Qui, ab aspernatur. Obcaecati quam, odit dignissimos molestiae rerum ipsam officia quidem nemo reiciendis ipsum veritatis porro consectetur ipsa consequatur itaque neque magni error soluta temporibus ad blanditiis dolor. Quod!
        Tempore error, minus modi veritatis consectetur qui repellendus asperiores sit quae voluptatem, nisi possimus beatae vitae culpa rerum quasi! Libero sed velit illum ea. Voluptatibus eaque error accusantium ut nam!
        Similique vel, voluptatum tenetur a praesentium sunt obcaecati deserunt nostrum minima sapiente in incidunt voluptatem modi dolorum ipsa assumenda earum pariatur? Praesentium commodi magnam necessitatibus blanditiis possimus sapiente aspernatur adipisci.
        Beatae aspernatur exercitationem enim officiis consectetur, dolorem ducimus architecto incidunt explicabo illum optio, non iste quidem consequatur quos voluptatem perspiciatis sapiente dolore, consequuntur modi. Porro, velit a! Necessitatibus, quam asperiores?
        Minus officiis voluptatibus eos ipsam, quos, minima voluptate quod iure in atque maxime sapiente assumenda id odit culpa, amet magnam provident placeat eligendi dolor velit rem ipsum voluptatem impedit! Voluptatem?
        Omnis quisquam optio velit nihil iste ipsam, fuga placeat explicabo ad voluptate impedit reprehenderit necessitatibus nemo accusantium nostrum possimus, eveniet provident ratione maxime corporis voluptas totam labore veniam. Eveniet, molestias.
        Obcaecati numquam eos itaque aliquam, dolore illo nemo ipsum soluta ullam voluptas officiis tempora voluptatibus voluptates. Quisquam quae esse dolores nihil sunt enim totam, ratione ipsa tenetur sed. Impedit, libero?
        Voluptas aliquam harum et. Reprehenderit modi id quas nemo animi earum suscipit blanditiis sapiente distinctio, cum quam quo illo architecto repellendus corporis asperiores inventore necessitatibus? Eaque atque incidunt sed cumque?
        A voluptatibus dolorum cumque dolores tempore dicta totam ut doloribus, recusandae sint ad excepturi, suscipit soluta odit? Pariatur in culpa recusandae cumque, voluptas voluptatum cum sapiente debitis, ipsam, aspernatur dolorum?
        Impedit omnis praesentium quaerat esse, architecto quod eum fuga possimus consequuntur, minima, illo nemo ipsa. Quibusdam harum dolor nostrum fugit. Eius consequuntur eligendi dolores ab, ipsam dolore incidunt dolor distinctio!
        Officiis velit pariatur rerum aliquid nostrum asperiores quas similique perferendis architecto ullam quidem eligendi quos at eius dolore, distinctio iste. Fuga placeat ab sapiente dolore consequatur quibusdam beatae ut iure.
        Tempora nobis quam sunt similique assumenda repudiandae maxime explicabo doloremque eos, numquam quidem quia possimus dicta tenetur itaque delectus! Obcaecati tenetur dolore vitae optio asperiores dolores laboriosam et. Magni, laborum!
        Maxime non, labore et veritatis perferendis cupiditate quibusdam? Quasi molestias maxime obcaecati voluptate earum molestiae fugiat libero voluptates repellat eos ad est vero assumenda, modi odit! Illo ipsa officiis cumque.
        Aut earum laborum possimus culpa rem nemo adipisci hic reiciendis quisquam velit sit aliquid error, labore quaerat distinctio exercitationem commodi enim quos consequuntur nam inventore fuga praesentium. Et, reprehenderit assumenda.
        Sapiente voluptate, totam repudiandae aspernatur perspiciatis alias possimus quam ex quibusdam, voluptates nulla quod. Rerum officia iste quas necessitatibus, maxime officiis? Officiis, nam. Asperiores delectus quidem provident accusantium cumque possimus!
        Ratione sequi ad soluta qui voluptatum beatae rerum animi eaque perspiciatis quasi ut voluptatibus voluptate, ullam dolores doloremque assumenda sint veritatis consequuntur eligendi. Fugit quis veniam voluptatibus dolores placeat ratione.
        Quas laudantium iusto, consectetur repellat cumque delectus officiis doloremque omnis dolor earum. Laborum ratione perspiciatis cum quibusdam nulla consectetur ab minus nemo odit ad itaque mollitia deserunt impedit, veniam quae?
        Accusantium a itaque, reprehenderit ullam hic facilis voluptatum natus tempora inventore numquam. Velit ratione, autem nisi dolorem nihil beatae. Totam eos aut, ducimus dolorum nulla velit autem cupiditate distinctio explicabo!
        Debitis quibusdam ullam fugiat dolores minus quo obcaecati, deserunt id incidunt nemo in laborum cumque atque consequatur deleniti quis, fugit dolor similique nisi neque accusamus quaerat doloremque eius. Tenetur, voluptates!
        Tenetur ut assumenda, aliquam mollitia error iste voluptas dicta aut placeat magnam architecto natus ducimus beatae, sunt nisi exercitationem similique tempora, quidem impedit veniam laboriosam quasi. Molestiae, dolorem doloribus? Nobis!
        Molestiae magnam possimus labore quibusdam maiores soluta unde adipisci mollitia quasi ducimus rem, eum hic amet assumenda distinctio! Aspernatur similique placeat doloribus reprehenderit tempore est maiores sit, obcaecati rem recusandae.
        Dolores recusandae est asperiores, ipsa reprehenderit, architecto quo fugit dignissimos ea iste quas sed culpa eveniet corrupti ad! Dolores libero eius numquam id nostrum quisquam corrupti beatae consequatur vitae optio?
        Amet praesentium soluta dicta expedita quasi neque at quam quisquam quia temporibus ipsa obcaecati doloremque totam et aliquam, adipisci aliquid quaerat perspiciatis autem dignissimos consequuntur quae. In deleniti eos nam?
        Natus, iure. At voluptates ducimus nihil sit minima veniam perspiciatis, aut aspernatur voluptatibus nulla possimus repellendus optio voluptatum perferendis quis eius quidem suscipit nisi dolorum? Maxime, expedita. Hic, perferendis iste.
        Dignissimos quam cumque repellendus unde error eum harum fuga quibusdam non voluptatum voluptatibus porro ea natus quasi veniam, dicta quo laudantium nisi reiciendis? Vero, nulla. Alias, autem saepe. Explicabo, quod?
        Quos velit quia mollitia commodi soluta, cum, harum similique dolore perspiciatis sit corporis fugiat repellendus doloribus ipsam cupiditate accusantium autem consectetur id iste dicta alias ex recusandae. Suscipit, nemo veritatis!
        Sit maiores quas, ab ratione quam architecto! Suscipit, unde architecto laboriosam facilis inventore quos maxime possimus delectus animi quisquam reiciendis nam voluptates neque tenetur sapiente numquam, officiis nesciunt hic beatae.
        Cumque quos earum nemo suscipit minima. Velit, labore iste quia nostrum officia dicta perferendis sunt ipsa quas modi, porro reprehenderit rerum dolores adipisci assumenda nam eaque vitae, molestiae cupiditate hic.
        Sapiente voluptatum consequuntur molestiae. Quisquam quia veritatis quasi expedita magnam accusamus quaerat voluptatibus odit, architecto accusantium magni mollitia repellat a laudantium vero dolorum saepe facere sunt. Maiores nam accusantium sequi?
        Voluptates, odit sequi molestiae at alias ipsam incidunt accusantium sunt impedit tenetur animi ea expedita sed aliquam eveniet officiis culpa. Nisi qui maiores omnis ab id aliquid voluptatibus? Consectetur, dolore.
        Labore, quis ullam perferendis, beatae exercitationem voluptatibus natus odit iure voluptates in repudiandae numquam recusandae asperiores, reprehenderit inventore dolore praesentium pariatur omnis rerum vero quo fugiat quae blanditiis aliquid. Excepturi.
        Temporibus porro rerum sint voluptatem laudantium reiciendis fugit voluptas provident corporis optio quae molestias suscipit similique deserunt unde quisquam quos culpa dolore distinctio, obcaecati impedit modi nesciunt ducimus. Cum, autem.
        Accusamus ipsa, libero quisquam saepe, fugit qui numquam eum tenetur, enim hic non. Molestias nemo aperiam perspiciatis iste dicta nisi esse minus, ratione doloribus vitae exercitationem necessitatibus distinctio illo atque.
        Ipsam, similique repudiandae distinctio a corporis exercitationem optio quae aspernatur culpa dolorem quo eius tenetur fugit laborum. Nisi ab error, ipsam et quia provident ipsa quaerat dolorum modi doloribus maxime.
        Aspernatur, doloribus, ipsam voluptate architecto corrupti nisi itaque officia dolorem voluptates, tempore perspiciatis molestias maiores quis aliquid deserunt. Earum eligendi quos laudantium quasi, quis sapiente tempora sequi vero tenetur molestias?
        Culpa tempore voluptatum natus temporibus, voluptatibus saepe odit similique, iure, eum quia cum adipisci doloribus eligendi aperiam maxime laboriosam corporis nam? Illum, nulla. Autem veniam optio sapiente excepturi? Ipsa, excepturi?
        Tempore cumque obcaecati cupiditate illo eos sequi facere vitae, mollitia consequatur dolor! Labore doloribus sapiente cum, magnam reprehenderit expedita quae mollitia voluptate illo accusantium iure, nobis, fugit assumenda quibusdam delectus.
        Eveniet atque iusto rem laudantium esse voluptates, qui excepturi quod alias ad? Aliquid iste, accusamus, dignissimos similique tempora est quibusdam expedita ullam saepe dolor labore velit praesentium inventore aspernatur blanditiis?
        Doloribus illum ut repellendus accusantium, nesciunt laboriosam ab placeat ipsa cumque reiciendis quos eos! Veniam doloribus aperiam nostrum atque aliquam odio voluptatum et illum, sapiente ratione minima nulla hic! Delectus!
        Recusandae sit quasi sunt totam eaque perferendis magni obcaecati eum, quod unde soluta repellendus quam ea eveniet deserunt amet molestiae neque ipsa est corrupti esse non itaque! Esse, facere a?
        Natus totam similique quis dolores tempore eaque, id voluptate? Quidem culpa iusto minus, atque animi pariatur aut ad, eligendi maxime ipsa, cum perferendis. Quisquam consequatur architecto aut distinctio harum beatae.
        Optio libero sunt eligendi dolores ea, dignissimos expedita omnis iusto molestias iste deserunt alias provident, veritatis recusandae facilis commodi? Vitae error debitis rerum provident sit ea pariatur aperiam soluta nihil?
        Doloremque aperiam repudiandae voluptatem officiis quo omnis ipsum, facere, ullam pariatur quisquam dolor, modi voluptate velit illum quasi alias mollitia atque maiores iure delectus deserunt quae doloribus! Ratione, vel asperiores?
        Perferendis a animi, libero nam sint id maxime ipsum, quisquam reiciendis debitis vero numquam. Libero deleniti earum, assumenda et laborum ratione pariatur tempore molestias, est minima, placeat fuga accusamus asperiores.
        Nulla explicabo eveniet tempore ex repellat et molestiae natus magnam fugit velit quia fugiat dolorum deserunt tempora, cumque provident. A, ex! Doloribus libero corrupti laborum, ea vero labore doloremque! Perspiciatis.
        Beatae enim magnam molestiae deleniti suscipit temporibus eius quas aperiam eveniet. In, minima. Nostrum atque id magnam quidem quis. Sunt suscipit consectetur porro tempore molestias culpa iusto voluptatibus praesentium aperiam.
        Ullam, vitae. Enim reiciendis adipisci vel odit ipsa dolores blanditiis labore error rerum inventore sed, veniam modi totam suscipit deserunt obcaecati officia eaque qui fugiat veritatis. Sed accusantium harum illo!
        Aspernatur distinctio, asperiores quas placeat molestias doloribus dicta modi tempore provident adipisci iure eum harum perspiciatis, eaque quia voluptas quasi obcaecati magnam deleniti fugiat fuga et? Eligendi itaque veritatis sequi.
        Atque quas dignissimos praesentium quidem. Voluptates asperiores velit deleniti laborum consectetur qui amet, molestias commodi ullam tempora corrupti explicabo veniam nobis, itaque est mollitia iste a officiis sunt accusantium distinctio.
        Temporibus consectetur sequi voluptatem cumque veniam quibusdam, non recusandae adipisci impedit eos molestiae delectus alias modi, quasi quos consequuntur, enim facilis! Corporis fuga, perferendis provident quas sequi necessitatibus? Beatae, repellendus?
        Quisquam at nulla consequuntur velit blanditiis ea amet culpa, qui minima dolorum quam a? Deserunt iure repellat beatae maxime odit quae odio, vel magni perferendis. Delectus quis possimus dicta quod.
        Dolores, rem nobis iusto deserunt reprehenderit asperiores beatae provident sequi, officiis fugit maxime? Provident magni autem ut? Id quas magni, eveniet dicta voluptatibus repellendus molestias eaque, expedita, iste error repellat!
        Laboriosam exercitationem maiores cum soluta ipsa cupiditate voluptates, et harum quos natus quod! Possimus consequatur quasi consequuntur, fugiat earum hic, saepe necessitatibus eveniet, magnam repellat vitae perspiciatis porro in incidunt!
        In animi expedita nisi consequuntur iure assumenda, impedit totam esse corporis nulla iusto quisquam facere architecto, vel maxime ut cum reiciendis maiores, mollitia libero quasi aut magnam? Voluptatum, mollitia blanditiis!
        Iusto repellendus fuga quis vel aliquam doloremque quasi, laboriosam at consequatur blanditiis enim ea nihil optio maxime illum dolorum architecto. Tenetur ab, et doloribus voluptas libero debitis consequuntur qui? Sunt.
        Voluptas saepe quasi cupiditate molestias voluptatibus, obcaecati distinctio ut. A facilis corrupti, officia tempora ipsa placeat ratione nesciunt natus exercitationem mollitia animi ipsum autem quidem soluta sequi iste, aliquam doloremque!
        Commodi, consectetur incidunt libero, non in, ab aperiam est quod et accusamus unde eos pariatur voluptate error? Veniam id voluptates tenetur ipsam earum nisi beatae dolorem, illo repellendus quo obcaecati!
        Illo rem libero voluptatum velit, itaque, suscipit, sed magni dolore laborum sapiente delectus fuga non ut sequi. Laboriosam, explicabo consectetur aspernatur modi pariatur ratione et doloribus illo eveniet fugit repellat?
      </Card>
    </main>
  )
}

export default BlogMain